# Generated by Django 4.2.7 on 2024-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catefory',
            new_name='category',
        ),
    ]
