# Generated by Django 4.2.7 on 2024-03-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0002_rename_catefory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=200, unique=True),
        ),
    ]
