# Generated by Django 4.2.7 on 2024-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash on Delivery', max_length=20),
        ),
    ]
