# Generated by Django 4.2.7 on 2024-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0009_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
