# Generated by Django 4.2.7 on 2024-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0010_order_order_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cancel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
