# Generated by Django 4.2.7 on 2024-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGurkha', '0011_alter_order_order_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_cancel',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
